<a href="https://colab.research.google.com/github/SantiagoVillalobosB/Machine_Learning_2022/blob/Main/PROYECTO_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Importación de librerias**

In [2]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
from sklearn.linear_model import LinearRegression, LogisticRegression 
from sklearn.svm import SVC 
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from scipy.spatial.distance import mahalanobis
from scipy.stats import chi2
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
import warnings
from sklearn.cluster import KMeans
from sklearn.metrics import pairwise_distances_argmin_min
from sklearn import tree
from sklearn.metrics import accuracy_score 
from sklearn.model_selection import cross_val_score
from IPython.display import Image as PImage 
from sklearn.preprocessing import StandardScaler
from sklearn import svm
warnings.filterwarnings("ignore")

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/labeconometria/proyectos/main/economicas.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3855 entries, 0 to 3854
Data columns (total 97 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   ESTU_CONSECUTIVO                3855 non-null   object 
 1   RESULT_CODIGOPRUEBA             3855 non-null   int64  
 2   RESULT_NOMBREPRUEBA             3855 non-null   object 
 3   RESULT_PUNTAJE                  3855 non-null   int64  
 4   RESULT_DESEMPENO                3855 non-null   int64  
 5   ESTU_AGREGADO                   3855 non-null   object 
 6   ESTU_TIPODOCUMENTO              3855 non-null   object 
 7   ESTU_NACIONALIDAD               3855 non-null   object 
 8   ESTU_GENERO                     3855 non-null   object 
 9   ESTU_FECHANACIMIENTO            3855 non-null   object 
 10  ESTU_EXTERIOR                   3855 non-null   object 
 11  PERIODO                         3855 non-null   int64  
 12  ESTU_ESTUDIANTE                 38

In [5]:
df.drop(['ESTU_CONSECUTIVO', 'RESULT_CODIGOPRUEBA', 'RESULT_NOMBREPRUEBA', 'RESULT_PUNTAJE', 'RESULT_DESEMPENO', 'ESTU_AGREGADO', 'ESTU_FECHANACIMIENTO', 'PERIODO', 'ESTU_ESTUDIANTE', 'ESTU_PAIS_RESIDE','ESTU_COD_RESIDE_DEPTO', 'ESTU_MCPIO_RESIDE', 'ESTU_COD_RESIDE_MCPIO', 'ESTU_AREARESIDE', 'ESTU_COLE_TERMINO', 'ESTU_CODDANE_COLE_TERMINO', 'ESTU_COD_COLE_MCPIO_TERMINO', 'ESTU_TITULOOBTENIDOBACHILLER',  'ESTU_COMOCAPACITOEXAMENSB11', 'ESTU_TIPODOCUMENTOSB11','ESTU_OTROCOLE_TERMINO', 'FAMI_TIENELAVADORA', 'FAMI_TIENEHORNOMICROOGAS', 'FAMI_TIENESERVICIOTV', 'FAMI_TIENEAUTOMOVIL', 'FAMI_TIENEMOTOCICLETA', 'FAMI_TIENECONSOLAVIDEOJUEGOS', 'FAMI_CUANTOSCOMPARTEBAÑO', 'ESTU_PRESENTACIONCASA', 'ESTU_PAISDOCUMENTOS11', 'ESTU_HORASSEMANATRABAJA', 'INST_COD_INSTITUCION', 'INST_NOMBRE_INSTITUCION','ESTU_SNIES_PRGMACADEMICO', 'GRUPOREFERENCIA', 'ESTU_PRGM_CODMUNICIPIO', 'ESTU_PRGM_MUNICIPIO', 'ESTU_PRGM_DEPARTAMENTO', 'ESTU_NIVEL_PRGM_ACADEMICO', 'ESTU_METODO_PRGM', 'ESTU_NUCLEO_PREGRADO', 'ESTU_INST_CODMUNICIPIO', 'ESTU_INST_MUNICIPIO', 'ESTU_INST_DEPARTAMENTO', 'INST_CARACTER_ACADEMICO', 'INST_ORIGEN', 'ESTU_PRIVADO_LIBERTAD', 'ESTU_COD_MCPIO_PRESENTACION', 'ESTU_MCPIO_PRESENTACION', 'ESTU_DEPTO_PRESENTACION', 'ESTU_COD_DEPTO_PRESENTACION','MOD_RAZONA_CUANTITAT_DESEM', 'MOD_RAZONA_CUANTITATIVO_PNAL', 'MOD_RAZONA_CUANTITATIVO_PNBC', 'MOD_LECTURA_CRITICA_DESEM', 'MOD_LECTURA_CRITICA_PNAL', 'MOD_LECTURA_CRITICA_PNBC', 'MOD_COMPETEN_CIUDADA_DESEM', 'MOD_COMPETEN_CIUDADA_PNAL','MOD_COMPETEN_CIUDADA_PNBC','MOD_INGLES_DESEM', 'MOD_INGLES_PNAL', 'MOD_INGLES_PNBC', 'MOD_COMUNI_ESCRITA_DESEM', 'MOD_COMUNI_ESCRITA_PNAL', 'MOD_COMUNI_ESCRITA_PNBC',  'PERCENTIL_NBC', 'PERCENTIL_GLOBAL', 'ESTU_INSE_INDIVIDUAL', 'ESTU_NSE_INDIVIDUAL', 'ESTU_NSE_IES', 'ESTU_ESTADOINVESTIGACION'], axis=1, inplace=True)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3855 entries, 0 to 3854
Data columns (total 25 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   ESTU_TIPODOCUMENTO              3855 non-null   object
 1   ESTU_NACIONALIDAD               3855 non-null   object
 2   ESTU_GENERO                     3855 non-null   object
 3   ESTU_EXTERIOR                   3855 non-null   object
 4   ESTU_DEPTO_RESIDE               3855 non-null   object
 5   ESTU_VALORMATRICULAUNIVERSIDAD  3850 non-null   object
 6   ESTU_PAGOMATRICULABECA          3850 non-null   object
 7   ESTU_PAGOMATRICULACREDITO       3850 non-null   object
 8   ESTU_PAGOMATRICULAPADRES        3850 non-null   object
 9   ESTU_PAGOMATRICULAPROPIO        3850 non-null   object
 10  ESTU_SEMESTRECURSA              3850 non-null   object
 11  FAMI_EDUCACIONPADRE             3760 non-null   object
 12  FAMI_EDUCACIONMADRE             3755 non-null   

In [7]:
print(f'cantidad de datos del dataset original contando todos los posibles duplicados: {df.shape}')
df.drop_duplicates(inplace = True)
print(f'cantidad de datos del dataset original cuando ya se reviso si habia datos suplicados:  {df.shape}')

cantidad de datos del dataset original contando todos los posibles duplicados: (3855, 25)
cantidad de datos del dataset original cuando ya se reviso si habia datos suplicados:  (3855, 25)


In [8]:
df.isnull().sum()

ESTU_TIPODOCUMENTO                  0
ESTU_NACIONALIDAD                   0
ESTU_GENERO                         0
ESTU_EXTERIOR                       0
ESTU_DEPTO_RESIDE                   0
ESTU_VALORMATRICULAUNIVERSIDAD      5
ESTU_PAGOMATRICULABECA              5
ESTU_PAGOMATRICULACREDITO           5
ESTU_PAGOMATRICULAPADRES            5
ESTU_PAGOMATRICULAPROPIO            5
ESTU_SEMESTRECURSA                  5
FAMI_EDUCACIONPADRE                95
FAMI_EDUCACIONMADRE               100
FAMI_TRABAJOLABORPADRE            404
FAMI_TRABAJOLABORMADRE            244
FAMI_ESTRATOVIVIENDA              134
FAMI_TIENEINTERNET                132
FAMI_TIENECOMPUTADOR              372
ESTU_PRGM_ACADEMICO                 0
MOD_RAZONA_CUANTITAT_PUNT           0
MOD_LECTURA_CRITICA_PUNT            0
MOD_COMPETEN_CIUDADA_PUNT           0
MOD_INGLES_PUNT                     0
MOD_COMUNI_ESCRITA_PUNT             0
PUNT_GLOBAL                         0
dtype: int64

In [9]:
df.dropna(subset=['ESTU_VALORMATRICULAUNIVERSIDAD','ESTU_PAGOMATRICULABECA','ESTU_PAGOMATRICULACREDITO','ESTU_PAGOMATRICULAPADRES','ESTU_PAGOMATRICULAPROPIO','ESTU_SEMESTRECURSA','FAMI_EDUCACIONMADRE','FAMI_TRABAJOLABORPADRE','FAMI_TRABAJOLABORMADRE', 'FAMI_ESTRATOVIVIENDA','FAMI_TIENEINTERNET','FAMI_TIENECOMPUTADOR'], inplace=True)

In [10]:
df.isnull().sum()

ESTU_TIPODOCUMENTO                0
ESTU_NACIONALIDAD                 0
ESTU_GENERO                       0
ESTU_EXTERIOR                     0
ESTU_DEPTO_RESIDE                 0
ESTU_VALORMATRICULAUNIVERSIDAD    0
ESTU_PAGOMATRICULABECA            0
ESTU_PAGOMATRICULACREDITO         0
ESTU_PAGOMATRICULAPADRES          0
ESTU_PAGOMATRICULAPROPIO          0
ESTU_SEMESTRECURSA                0
FAMI_EDUCACIONPADRE               0
FAMI_EDUCACIONMADRE               0
FAMI_TRABAJOLABORPADRE            0
FAMI_TRABAJOLABORMADRE            0
FAMI_ESTRATOVIVIENDA              0
FAMI_TIENEINTERNET                0
FAMI_TIENECOMPUTADOR              0
ESTU_PRGM_ACADEMICO               0
MOD_RAZONA_CUANTITAT_PUNT         0
MOD_LECTURA_CRITICA_PUNT          0
MOD_COMPETEN_CIUDADA_PUNT         0
MOD_INGLES_PUNT                   0
MOD_COMUNI_ESCRITA_PUNT           0
PUNT_GLOBAL                       0
dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3129 entries, 1 to 3850
Data columns (total 25 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   ESTU_TIPODOCUMENTO              3129 non-null   object
 1   ESTU_NACIONALIDAD               3129 non-null   object
 2   ESTU_GENERO                     3129 non-null   object
 3   ESTU_EXTERIOR                   3129 non-null   object
 4   ESTU_DEPTO_RESIDE               3129 non-null   object
 5   ESTU_VALORMATRICULAUNIVERSIDAD  3129 non-null   object
 6   ESTU_PAGOMATRICULABECA          3129 non-null   object
 7   ESTU_PAGOMATRICULACREDITO       3129 non-null   object
 8   ESTU_PAGOMATRICULAPADRES        3129 non-null   object
 9   ESTU_PAGOMATRICULAPROPIO        3129 non-null   object
 10  ESTU_SEMESTRECURSA              3129 non-null   object
 11  FAMI_EDUCACIONPADRE             3129 non-null   object
 12  FAMI_EDUCACIONMADRE             3129 non-null   

In [12]:
df.fillna(method='ffill')

ESTU_TIPODOCUMENTO ESTU_NACIONALIDAD ESTU_GENERO ESTU_EXTERIOR  \
1                    CC          COLOMBIA           M            NO   
3                    CC          COLOMBIA           F            NO   
4                    CC          COLOMBIA           M            NO   
5                    CC          COLOMBIA           F            NO   
6                    CC          COLOMBIA           M            NO   
...                 ...               ...         ...           ...   
3846                 CC          COLOMBIA           M            NO   
3847                 CC          COLOMBIA           M            NO   
3848                 CC          COLOMBIA           M            NO   
3849                 CC          COLOMBIA           M            NO   
3850                 CC          COLOMBIA           M            NO   

     ESTU_DEPTO_RESIDE            ESTU_VALORMATRICULAUNIVERSIDAD  \
1               BOGOTÁ                         Más de 7 millones   
3               BOGOTÁ    Entre 1 millón y menos de 2.5 millones   
4               BOGOTÁ  Entre 4 millones y menos de 5.5 millones   
5               BOGOTÁ  Entre 2.5 millones y menos de 4 millones   
6                VALLE    Entre 1 millón y menos de 2.5 millones   
...                ...                                       ...   
3846            BOGOTÁ                          Menos de 500 mil   
3847            CALDAS  Entre 2.5 millones y menos de 4 millones   
3848            BOGOTÁ  Entre 2.5 millones y menos de 4 millones   
3849            BOGOTÁ  Entre 5.5 millones y menos de 7 millones   
3850             VALLE                         Más de 7 millones   

     ESTU_PAGOMATRICULABECA ESTU_PAGOMATRICULACREDITO  \
1                        No                        No   
3                        No                        Si   
4                        No                        No   
5                        No                        No   
6                        No                        Si   
...                     ...                       ...   
3846                     No                        No   
3847                     No                        Si   
3848                     No                        Si   
3849                     No                        Si   
3850                     No                        No   

     ESTU_PAGOMATRICULAPADRES ESTU_PAGOMATRICULAPROPIO  ...  \
1                          Si                       No  ...   
3                          No                       No  ...   
4                          No                       Si  ...   
5                          No                       Si  ...   
6                          Si                       Si  ...   
...                       ...                      ...  ...   
3846                       Si                       Si  ...   
3847                       No                       No  ...   
3848                       No                       Si  ...   
3849                       Si                       Si  ...   
3850                       Si                       No  ...   

     FAMI_ESTRATOVIVIENDA FAMI_TIENEINTERNET FAMI_TIENECOMPUTADOR  \
1               Estrato 4                 Si                   Si   
3               Estrato 3                 Si                   Si   
4               Estrato 3                 Si                   Si   
5               Estrato 2                 Si                   Si   
6               Estrato 3                 Si                   No   
...                   ...                ...                  ...   
3846            Estrato 3                 Si                   Si   
3847            Estrato 3                 Si                   Si   
3848            Estrato 3                 Si                   Si   
3849            Estrato 3                 Si                   Si   
3850            Estrato 5                 Si                   Si   

           ESTU_PRGM_ACADEMICO MOD_RAZONA_CUANTITAT_PUNT  \
1   

In [18]:
datos=df.drop(['ESTU_TIPODOCUMENTO','ESTU_NACIONALIDAD','ESTU_GENERO','ESTU_EXTERIOR','ESTU_DEPTO_RESIDE','ESTU_VALORMATRICULAUNIVERSIDAD','ESTU_PAGOMATRICULABECA','ESTU_PAGOMATRICULACREDITO','ESTU_PAGOMATRICULAPADRES','ESTU_PAGOMATRICULAPROPIO','ESTU_SEMESTRECURSA','FAMI_EDUCACIONPADRE','FAMI_EDUCACIONMADRE','FAMI_TRABAJOLABORPADRE','FAMI_TRABAJOLABORMADRE','FAMI_ESTRATOVIVIENDA','FAMI_TIENEINTERNET','FAMI_TIENECOMPUTADOR','ESTU_PRGM_ACADEMICO'],axis=1)

In [19]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3129 entries, 1 to 3850
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   MOD_RAZONA_CUANTITAT_PUNT  3129 non-null   int64
 1   MOD_LECTURA_CRITICA_PUNT   3129 non-null   int64
 2   MOD_COMPETEN_CIUDADA_PUNT  3129 non-null   int64
 3   MOD_INGLES_PUNT            3129 non-null   int64
 4   MOD_COMUNI_ESCRITA_PUNT    3129 non-null   int64
 5   PUNT_GLOBAL                3129 non-null   int64
dtypes: int64(6)
memory usage: 171.1 KB


In [20]:
kmeans = KMeans(n_clusters=2, random_state=0).fit(datos)

In [21]:
y=kmeans.labels_

In [22]:
y

array([1, 0, 0, ..., 0, 1, 1], dtype=int32)

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train, x_test, y_train, y_test = train_test_split(datos, y, test_size=4, random_state=4)

In [25]:
print(x_train.shape)
print(x_test.shape)

(3125, 6)
(4, 6)


In [26]:
x_train

MOD_RAZONA_CUANTITAT_PUNT  MOD_LECTURA_CRITICA_PUNT  \
3571                        139                       167   
2578                        172                       188   
1020                        194                       189   
3241                        142                       102   
103                         120                       140   
...                         ...                       ...   
2330                        186                       189   
834                         136                       125   
3041                        188                       189   
198                         181                       193   
1367                        125                       118   

      MOD_COMPETEN_CIUDADA_PUNT  MOD_INGLES_PUNT  MOD_COMUNI_ESCRITA_PUNT  \
3571                        145              160                      145   
2578                        189              209                      179   
1020                        210              213                      300   
3241                        124              131                      116   
103                         173              126                      145   
...                         ...              ...                      ...   
2330                        161              190                      194   
834                         132              144                      129   
3041                        205              175                      143   
198                         179              209                      134   
1367                         88              174                      133   

      PUNT_GLOBAL  
3571          151  
2578          187  
1020          221  
3241          123  
103           141  
...           ...  
2330          184  
834           133  
3041          180  
198           179  
1367          128  

[3125 rows x 6 columns]

In [27]:
scaler=StandardScaler()
print(scaler.fit(x_train))
x_train=scaler.transform(x_train)

StandardScaler()


In [28]:
print(scaler.mean_)

[162.71072 160.25984 159.91744 174.53504 150.69984 161.62944]


In [29]:
x_train

array([[-0.72992633,  0.20816766, -0.43479718, -0.4320586 , -0.1407599 ,
        -0.39726365],
       [ 0.28596728,  0.85674586,  0.84766657,  1.0244817 ,  0.69888411,
         0.94819682],
       [ 0.96322968,  0.88763054,  1.45975154,  1.14338295,  3.68702898,
         2.21890949],
       ...,
       [ 0.77852176,  0.88763054,  1.31401703,  0.01382108, -0.19015072,
         0.68657951],
       [ 0.56302917,  1.01116925,  0.55619753,  1.0244817 , -0.41240943,
         0.64920561],
       [-1.1609115 , -1.30518148, -2.09617068, -0.01590423, -0.43710484,
        -1.25686339]])

In [30]:
clf=svm.SVC(kernel='linear',probability=True)
clf.fit(x_train,y_train)

SVC(kernel='linear', probability=True)

In [31]:
scaler=StandardScaler()
print(scaler.fit(x_test))
x_test=scaler.transform(x_test)

StandardScaler()


In [32]:
y_pred=clf.predict(x_test)

In [33]:
y_pred

array([0, 0, 1, 1], dtype=int32)