<a href="https://colab.research.google.com/github/SantiagoVillalobosB/Machine_Learning_2022/blob/Main/Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.metrics import accuracy_score 
from sklearn.model_selection import cross_val_score
from IPython.display import Image as PImage 
from sklearn.preprocessing import StandardScaler
from sklearn import svm

In [ ]:
x_train=pd.read_csv('https://raw.githubusercontent.com/cristiangp09/databases/main/train.csv')
x_test=pd.read_csv('https://raw.githubusercontent.com/cristiangp09/databases/main/test.csv')
resultados=pd.DataFrame(columns=['PassengerId','Survived'])
resultados['PassengerId']=x_test['PassengerId']

x_train.drop(columns=['PassengerId','Name','Ticket', 'Cabin','Embarked'],inplace=True)
x_test.drop(columns=['PassengerId','Name','Ticket', 'Cabin','Embarked'],inplace=True)
y_train=x_train['Survived']
x_train.drop(columns=['Survived'],inplace=True)
x_train['Sex'].replace({'male':1,'female':0},inplace=True)

x_test['Sex'].replace({'male':1,'female':0},inplace=True)
x_test['Fare'].replace({np.NaN:x_test['Fare'].mean()},inplace=True)
x_test['Age'].replace({np.NaN:x_test['Age'].mean()},inplace=True)

In [ ]:
x_train 

Pclass  Sex   Age  SibSp  Parch     Fare
0         3    1  22.0      1      0   7.2500
1         1    0  38.0      1      0  71.2833
2         3    0  26.0      0      0   7.9250
3         1    0  35.0      1      0  53.1000
4         3    1  35.0      0      0   8.0500
..      ...  ...   ...    ...    ...      ...
886       2    1  27.0      0      0  13.0000
887       1    0  19.0      0      0  30.0000
888       3    0   NaN      1      2  23.4500
889       1    1  26.0      0      0  30.0000
890       3    1  32.0      0      0   7.7500

[891 rows x 6 columns]

In [ ]:
resultados.shape

(418, 2)

In [ ]:
x_train

Pclass  Sex   Age  SibSp  Parch     Fare
0         3    1  22.0      1      0   7.2500
1         1    0  38.0      1      0  71.2833
2         3    0  26.0      0      0   7.9250
3         1    0  35.0      1      0  53.1000
4         3    1  35.0      0      0   8.0500
..      ...  ...   ...    ...    ...      ...
886       2    1  27.0      0      0  13.0000
887       1    0  19.0      0      0  30.0000
888       3    0   NaN      1      2  23.4500
889       1    1  26.0      0      0  30.0000
890       3    1  32.0      0      0   7.7500

[891 rows x 6 columns]

In [ ]:
x_test

Pclass  Sex       Age  SibSp  Parch      Fare
0         3    1  34.50000      0      0    7.8292
1         3    0  47.00000      1      0    7.0000
2         2    1  62.00000      0      0    9.6875
3         3    1  27.00000      0      0    8.6625
4         3    0  22.00000      1      1   12.2875
..      ...  ...       ...    ...    ...       ...
413       3    1  30.27259      0      0    8.0500
414       1    0  39.00000      0      0  108.9000
415       3    1  38.50000      0      0    7.2500
416       3    1  30.27259      0      0    8.0500
417       3    1  30.27259      1      1   22.3583

[418 rows x 6 columns]

In [ ]:
x_train['Age'].mean()
x_train['Age'].replace({np.NaN:x_train['Age'].mean()},inplace=True)

In [ ]:
scaler=StandardScaler()
print(scaler.fit(x_train))
x_train=scaler.transform(x_train)

StandardScaler()


In [ ]:
print(scaler.mean_)

[ 2.30864198  0.64758698 29.69911765  0.52300786  0.38159371 32.20420797]


In [ ]:
x_train

array([[ 0.82737724,  0.73769513, -0.5924806 ,  0.43279337, -0.47367361,
        -0.50244517],
       [-1.56610693, -1.35557354,  0.63878901,  0.43279337, -0.47367361,
         0.78684529],
       [ 0.82737724, -1.35557354, -0.2846632 , -0.4745452 , -0.47367361,
        -0.48885426],
       ...,
       [ 0.82737724, -1.35557354,  0.        ,  0.43279337,  2.00893337,
        -0.17626324],
       [-1.56610693,  0.73769513, -0.2846632 , -0.4745452 , -0.47367361,
        -0.04438104],
       [ 0.82737724,  0.73769513,  0.17706291, -0.4745452 , -0.47367361,
        -0.49237783]])

In [ ]:
clf=svm.SVC(kernel='linear',probability=True)
clf.fit(x_train,y_train)

SVC(kernel='linear', probability=True)

In [ ]:
scaler=StandardScaler()
print(scaler.fit(x_test))
x_test=scaler.transform(x_test)

StandardScaler()


In [ ]:
x_train.shape

(891, 6)

In [ ]:
x_test.shape

(418, 6)

In [ ]:
y_pred=clf.predict(x_test)

In [ ]:
y_pred

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [ ]:
y_pred

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [ ]:
resultados['Survived']=y_pred

In [ ]:
resultados

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [ ]:
resultados.to_csv('submission.csv',index=False)

In [ ]:
from xgboost import XGBClassifier, XGBRegressor

In [ ]:
xgb_c=XGBClassifier()
xgb_c.fit(x_train, y_train)
y_pred=xgb_c.predict(x_test)

In [ ]:
y_pred

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [ ]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn import svm 

param_grid={'kernel':['sigmoid','linear','rbf'],
            'decision_function_shape':['ovo','ovr']}

grid_search=GridSearchCV(svm.SVC(),param_grid,cv=6)
grid_search.fit(x_train,y_train)

GridSearchCV(cv=6, estimator=SVC(),
             param_grid={'decision_function_shape': ['ovo', 'ovr'],
                         'kernel': ['sigmoid', 'linear', 'rbf']})

In [ ]:
grid_search.best_params_

{'decision_function_shape': 'ovo', 'kernel': 'rbf'}

In [ ]:
clf=svm.SVC(kernel='rbf',decision_function_shape='ovo',probability=True)
clf.fit(x_train,y_train)

SVC(decision_function_shape='ovo', probability=True)

In [ ]:
y_pred=clf.predict(x_test)

In [ ]:
resultados['Survived']=y_pred

In [ ]:
resultados.to_csv('submission.csv',index=False)

In [ ]:
from sklearn.model_selection